---
title: "Script 2b"
subtitle: "Descriptive stats at each time interval"
author: "Peter Kamerman"
date: "`r format(Sys.Date(), '%d %B %Y')`"
geometry: margin=15mm
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(skimr)

# Skimr
skim_with(numeric = list(variable = NULL, hist = NULL))

# Set figures directory
if(!dir.exists('./figures')) {
    dir.create('./figures/')
}

if(!dir.exists('./figures/script-2b')) {
    dir.create('./figures/script-2b/')
}

# ggplot theme
theme_set(new = theme_bw(base_size = 18))

# knitr options
knitr::opts_chunk$set(fig.path = './figures/script-2b/')
```

----

# Objective 

To describe the demographic characteristics and disease status of the analysis cohort at each study assessment interval.

# Analysis notes

## Definitions of missingness

Data were regarded as **missing** when _pain in the last week_ data were not present for one or more of weeks 0, 12, 24, 36, 48. Data also were classified as **missing** when there were inconsistencies in the data across the variables collected within a week.

## Definition of data inconsistencies

Pain was defined as _pain in the last week_  being 'Yes', and _pain at its worst_ being > 0. These two measurements were then the "gatekeeper" measurements, such that the two measurements both had to be positive ('Yes' and '> 0', respectively) in order for there to be any entries for _site of pain_ and _site of worst pain_. Were the data were inconsistent (e.g., when there was no _pain in the last week_ and _pain at its worst_ = 0, but there were entries for _site of pain_ and _site of worst pain_), then the _site of pain_ and _site of worst pain_ entries were marked as **inconsistent**. 

Data also were considered **inconsistent** when _pain in the last week_ = 'Yes', but _site of worst pain_ = 'None'. 

Lastly, data were considered **inconsistent** when _site of worst pain_ was not listed as one of the pain locations for a given measurement week.

For analysis purposes, missing data in the _site of pain_ columns were changed to **'No'** (pain not present in the site). This approach was conservative, but we believed that the approach would have the least effect on the outcome, while still retaining as many participants as possible.


----

# Import data

```{r import}
df <- read_rds('data-cleaned/data-ADVANCE.rds') %>% 
    select(ranid, interval_name, pain_in_the_last_week, 
           cd4_cells.ul, viral_load_cp.ml,
           general_health, any_missing, interval_numeric)
```

# First look 

```{r inspect}
head(df)
glimpse(df)
```

# Basic clean

```{r clean}
# Clean and process data
df %<>% 
    filter(any_missing == 'No') %>% 
    select(-any_missing)
```

# Quick tabulation

## Analysis data set for the period 0 to 48 weeks

```{r quick_tab}
# Tabulate data
xtabs(~interval_name, data = df)
```

----

# Analysis

## Viral load

```{r vl}
# Tabulate data
df %>% 
  select(interval_name, viral_load_cp.ml) %>% 
  group_by(interval_name) %>% 
  skim_to_wide() %>% 
  select(-type, -variable) %>% 
  skimr::kable(caption = '5-number summary of viral load (copies/ml)')

# Plot data
df %>% 
  ggplot(data = .) +
  aes(x = factor(interval_numeric),
      y = viral_load_cp.ml) +
  geom_boxplot() +
  scale_y_log10() +
  labs(subtitle = 'Viral load',
       y = expression('Viral load [log'[10]*'(copies/ml)]'),
       x = 'Weeks')
```

## CD4 T-cell count

```{r cd4}
# Tabulate data
df %>% 
  filter(interval_numeric %in% c(0, 24, 48)) %>% 
  select(interval_name, cd4_cells.ul) %>% 
  group_by(interval_name) %>% 
  skim_to_wide() %>% 
  select(-type, -variable) %>% 
  skimr::kable(caption = '5-number summary of CD4 T-cell count (cells/ul)')

# Plot data
df %>% 
  filter(interval_numeric %in% c(0, 24, 48)) %>% 
  ggplot(data = .) +
  aes(x = factor(interval_numeric),
      y = cd4_cells.ul) +
  geom_boxplot() +
  labs(subtitle = 'CD4 T-cell count',
       y = 'CD4 count (cells/ul)',
       x = 'Weeks')
```

## General health

Rating of perceived health status on a 5-point Likert scale (1 = poor, 5 = excellent).

```{r gh}
# Tabulate data
df %>% 
  select(interval_name, general_health) %>% 
  group_by(interval_name) %>% 
  skim_to_wide() %>% 
  select(-type, -variable) %>% 
  skimr::kable(caption = '5-number summary of the general health score')

# Plot data
df %>% 
  ggplot(data = .) +
  aes(x = factor(interval_numeric),
      y = general_health) +
  geom_boxplot() +
  labs(subtitle = 'General health perception',
       y = 'GHP score (5-point Likert scale)',
       x = 'Weeks')
```

----

# Session information

```{r session_info}
sessionInfo()
```
