---
title: "Script 2a"
subtitle: "Descriptive statistics at enrolment"
author: "Peter Kamerman"
date: "`r format(Sys.Date(), '%d %B %Y')`"
geometry: margin=15mm
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(ggforce)
library(skimr)
library(patchwork)

# Configure skimr
skim_with(numeric = list(hist = NULL),
          character = list(min = NULL, max = NULL, empty = NULL))

# Set figures directory
if(!dir.exists('./figures')) {
    dir.create('./figures/')
}

if(!dir.exists('./figures/script-2a')) {
    dir.create('./figures/script-2a/')
}

# ggplot theme
theme_set(new = theme_bw(base_size = 18))

# Knitr options
knitr::opts_chunk$set(fig.path = './figures/script-2a/')
```

----

# Objective 

To describe the demographic characteristics and disease status of the analysis cohort at study enrolment (week 0, baseline).

# Analysis notes

## Definitions of missingness

Data were regarded as **missing** when _pain in the last week_ data were not present for one or more of weeks 0, 12, 24, 36, 48. Data also were classified as **missing** when there were inconsistencies in the data across the variables collected within a week.

## Definition of data inconsistencies

Pain was defined as _pain in the last week_  being 'Yes', and _pain at its worst_ being > 0. These two measurements were then the "gatekeeper" measurements, such that the two measurements both had to be positive ('Yes' and '> 0', respectively) in order for there to be any entries for _site of pain_ and _site of worst pain_. Were the data were inconsistent (e.g., when there was no _pain in the last week_ and _pain at its worst_ = 0, but there were entries for _site of pain_ and _site of worst pain_), then the _site of pain_ and _site of worst pain_ entries were marked as **inconsistent**. 

Data also were considered **inconsistent** when _pain in the last week_ = 'Yes', but _site of worst pain_ = 'None'. 

Lastly, data were considered **inconsistent** when _site of worst pain_ was not listed as one of the pain locations for a given measurement week.

For analysis purposes, missing data in the _site of pain_ columns were changed to **'No'** (pain not present in the site). This approach was conservative, but we believed that the approach would have the least effect on the outcome, while still retaining as many participants as possible.

----

# Import data

```{r import}
df <- read_rds('data-cleaned/data-ADVANCE.rds') 
```

# Quick look 

```{r inspect}
head(df)
glimpse(df)
```

# Basic clean

```{r clean}
# Remove missing data
df %<>%
    filter(any_missing == 'No')

# Extract enrolment data
df %<>%
    filter(interval_name == '0 weeks')
    ```

# Quick tabulation

## Analysis data set for the period 0 to 48 weeks

```{r quick3}
# Tabulate data
xtabs(~interval_name, data = df)
```

----

# Basic summary

```{r skim, results = 'asis'}
skim(df) %>% 
    skimr::kable(caption = 'Quick summary')
```

----

# Study characteristics

## Study site

```{r site}
# Plot
site_count <- ggplot(data = df) +
    aes(x = site_name) +
    geom_bar() +
    labs(subtitle = 'Study site: count',
         y = 'Count') +
    scale_x_discrete(labels = c('Hillbrow', 'Yeoville')) +
    theme(axis.title.x = element_blank())

site_prop <- df %>% 
    group_by(site_name) %>% 
    summarise(count = n()) %>% 
    ggplot(data = .) +
    aes(x = '',
        y = count,
        fill = site_name) +
    geom_col(position = position_fill()) +
    labs(subtitle = 'Study site: proportion',
         y = 'Proportion') +
    scale_fill_manual(values = c('#666666', '#CCCCCC'),
                      labels = c('Hillbrow', 'Yeoville')) +
    theme(legend.title = element_blank(),
          legend.text = element_text(size = 12),
          legend.position = 'top',
          axis.title.x = element_blank())

site_count + site_prop

# Numeric summary
df %>% 
    mutate(site_name = factor(site_name,
                              labels = c('Hillbrow', 'Yeoville'))) %>% 
    group_by(site_name) %>% 
    summarise(count = n()) %>% 
    mutate(n = sum(count),
           missing = sum(is.na(df$site_name))) %>% 
    mutate(proportion = round(count / n, 3)) %>% 
    select(site_name, count, n, missing, proportion) %>% 
    knitr::kable(caption = 'Study site: summary statistics')
```

## Treatment group allocation

```{r group, fig.height = 6}
# Plot
group_count <- ggplot(data = df) +
    aes(x = group) +
    geom_bar() +
    labs(subtitle = 'Treatment: count',
         y = 'Count') +
    scale_x_discrete(labels = c('DTG+TAF+FTC',
                                'DTG+TDF+FTC',
                                'EFV+TDF+FTC')) +
    theme(axis.title.x = element_blank(),
          axis.text.x = element_text(angle = 40, hjust = 1))

group_prop <- df %>% 
    group_by(group) %>% 
    summarise(count = n()) %>% 
    ggplot(data = .) +
    aes(x = 'All',
        y = count,
        fill = group) +
    geom_col(position = position_fill()) +
    labs(subtitle = 'Treatment: proportion',
         y = 'Proportion') +
    scale_fill_grey(guide = guide_legend(ncol = 1),
                    labels = c('DTG+TAF+FTC',
                               'DTG+TDF+FTC',
                               'EFV+TDF+FTC')) +
    theme(legend.title = element_blank(),
          legend.text = element_text(size = 12),
          legend.position = 'top',
          axis.title.x = element_blank())

group_count + group_prop

# Numeric summary
df %>% 
    select(group) %>% 
    group_by(group) %>% 
    summarise(count = n(),
              missing = sum(is.na(group))) %>% 
    mutate(n = sum(count),
           proportion = round(count / n, 3)) %>% 
    select(group, count, proportion, missing, n) %>% 
    knitr::kable(caption = 'Study group allocation: summary statistics')
```

----

# Demographics

## Age

```{r age, results = 'asis'}
# Plot
ggplot(data = df) +
    aes(x = 'Data',
        y = age) +
    geom_sina() +
    labs(subtitle = 'Age: density plot',
         y = 'Age (years)') +
    theme(axis.title.x = element_blank(),
          axis.text.x = element_blank())

# Numeric summary
df %>% 
    select(age) %>% 
    skim() %>% 
    skimr::kable(caption = 'Age: summary statistics')
```

## Sex

```{r sex, results = 'asis'}
# Plot
sex_count <- ggplot(data = df) +
    aes(x = sex) +
    geom_bar() +
    labs(subtitle = 'Sex: count',
         y = 'Count') +
    theme(axis.title.x = element_blank())
    
sex_prop <- df %>% 
    group_by(sex) %>% 
    summarise(count = n()) %>% 
    ggplot(data = .) +
    aes(x = 'Data',
        y = count,
        fill = sex) +
    geom_col(position = position_fill()) +
    labs(subtitle = 'Sex: proportion',
         y = 'Proportion') +
    scale_fill_grey() +
    theme(legend.title = element_blank(),
          legend.text = element_text(size = 12),
          legend.position = 'top',
          axis.title.x = element_blank(),
          axis.text.x = element_blank())

sex_count + sex_prop

# Numeric summary
df %>% 
    select(sex) %>% 
    mutate(sex = factor(sex)) %>% 
    skim() %>% 
    skimr::kable(caption = 'Sex: summary statistics')

df %>% 
    group_by(sex) %>% 
    summarise(count = n()) %>% 
    mutate(n = sum(count),
           missing = sum(is.na(df$sex))) %>% 
    mutate(proportion = round(count / n, 3)) %>% 
    select(sex, count, n, missing, proportion) %>% 
    knitr::kable(caption = 'Sex: summary statistics 2')
```

## Ancestry

```{r ancestry, results = 'asis'}
# Plot
anc_count <- ggplot(data = df) +
    aes(x = ancestry) +
    geom_bar() +
    labs(subtitle = 'Ancestry: count',
         y = 'Count') +
    theme(axis.title.x = element_blank())
    
anc_prop <- df %>% 
    group_by(ancestry) %>% 
    summarise(count = n()) %>% 
    ggplot(data = .) +
    aes(x = 'Data',
        y = count,
        fill = ancestry) +
    geom_col(position = position_fill()) +
    labs(subtitle = 'Ancestry: proportion',
         y = 'Proportion') +
    scale_fill_grey() +
    theme(legend.title = element_blank(),
          legend.text = element_text(size = 12),
          legend.position = 'top',
          axis.title.x = element_blank(),
          axis.text.x = element_blank())

anc_count + anc_prop

# Numeric summary
df %>% 
    select(ancestry) %>% 
    mutate(ancestry= factor(ancestry)) %>% 
    skim() %>%
    skimr::kable(caption = 'Ancestry: summary statistics')

df %>% 
    group_by(ancestry) %>% 
    summarise(count = n()) %>% 
    mutate(n = sum(count),
           missing = sum(is.na(df$ancestry))) %>% 
    mutate(proportion = round(count / n, 3)) %>% 
    select(ancestry, count, n, missing, proportion) %>% 
    knitr::kable(caption = 'Ancestry: summary statistics 2')
```

## Education

```{r edu, fig.height = 6, results = 'asis'}
# Plot
edu_count <- df %>% 
    mutate(education = str_replace_na(education)) %>% 
    mutate(education = factor(education,
                              levels = c('No schooling', 'Primary',
                                         'Secondary', 'Tertiary',
                                         'NA'),
                              ordered = TRUE)) %>% 
    ggplot(data = .) +
    aes(x = education,
        fill = education) +
    geom_bar() +
    labs(subtitle = 'Education: count',
         y = 'Count') +
        scale_fill_manual(values = c(rep('#666666', 4), '#FF0000')) +
    theme(legend.position = 'none',
          axis.title.x = element_blank(),
          axis.text.x = element_text(angle = 30, hjust = 1))

grey_pal <- colorRampPalette(colors = c('#CCCCCC', '#000000'),
                             interpolate = 'linear')
grey_red <- c(rev(grey_pal(4)), '#FF0000')
    
edu_prop <- df %>% 
    mutate(education = str_replace_na(education)) %>% 
    mutate(education = factor(education,
                              levels = c('No schooling', 'Primary',
                                         'Secondary', 'Tertiary',
                                         'NA'),
                              ordered = TRUE)) %>% 
    group_by(education) %>% 
    summarise(count = n()) %>% 
    ggplot(data = .) +
    aes(x = 'Data',
        y = count,
        fill = education) +
    geom_col(position = position_fill()) +
    labs(subtitle = 'Education: proportion',
         y = 'Proportion') +
    scale_fill_manual(values = grey_red,
                      guide = guide_legend(ncol = 2)) +
    theme(legend.title = element_blank(),
          legend.text = element_text(size = 12),
          legend.position = 'top',
          axis.title.x = element_blank(),
          axis.text.x = element_blank())

edu_count + edu_prop

# Numeric summary
df %>% 
    select(education) %>% 
    mutate(education = factor(education)) %>% 
    skim() %>% 
    skimr::kable(caption = 'Education: summary statistics')

df %>% 
    group_by(education) %>% 
    summarise(count = n()) %>% 
    mutate(n = sum(count),
           missing = sum(is.na(df$education)),
           n = n - missing) %>% 
    mutate(proportion = round(count / n, 3)) %>% 
    select(education, count, n, missing, proportion) %>% 
    filter(education != 'NA') %>% 
    knitr::kable(caption = 'Education: summary statistics 2')
```

## Employment

```{r emp, fig.height = 6, results = 'asis'}
# Plot
emp_count <- df %>% 
    mutate(employment_status = str_replace_na(employment_status)) %>% 
    mutate(employment_status = factor(employment_status,
                                      levels = c('Employed', 'Not Employed',
                                                 'Self-Employed', 'Schooling',
                                                 'NA'),
                                      ordered = TRUE)) %>% 
    ggplot(data = .) +
    aes(x = employment_status, 
        fill = employment_status) +
    geom_bar() +
    labs(subtitle = 'Employment: count',
         y = 'Count') +
    scale_fill_manual(values = c(rep('#666666', 4), '#FF0000')) +
    theme(legend.position = 'none',
          axis.title.x = element_blank(),
          axis.text.x = element_text(angle = 30, hjust = 1))
    
emp_prop <- df %>% 
    mutate(employment_status = str_replace_na(employment_status)) %>% 
    mutate(employment_status = factor(employment_status,
                                      levels = c('Employed', 'Not Employed',
                                                 'Self-Employed', 'Schooling',
                                                 'NA'),
                                      ordered = TRUE)) %>% 
    group_by(employment_status) %>% 
    summarise(count = n()) %>% 
    ggplot(data = .) +
    aes(x = 'Data',
        y = count,
        fill = employment_status) +
    geom_col(position = position_fill()) +
    labs(subtitle = 'Employment: proportion',
         y = 'Proportion') +
    scale_fill_manual(values = grey_red,
                      guide = guide_legend(ncol = 2)) +
    theme(legend.title = element_blank(),
          legend.text = element_text(size = 12),
          legend.position = 'top',
          axis.title.x = element_blank())

emp_count + emp_prop

# Numeric summary
df %>% 
    select(employment_status) %>% 
    mutate(employment_status = factor(employment_status)) %>% 
    skim() %>% 
    skimr::kable(caption = 'Employment status: summary statistics')

df %>% 
    group_by(employment_status) %>% 
    summarise(count = n()) %>% 
    mutate(n = sum(count),
           missing = sum(is.na(df$employment_status)),
           n = n - missing) %>% 
    mutate(proportion = round(count / n, 3)) %>% 
    select(employment_status, count, n, missing, proportion) %>% 
    filter(employment_status != 'NA') %>% 
    knitr::kable(caption = 'Employment status: summary statistics 2')
```

----

# Clinical

## CD4 T-cell count

```{r cd4, results = 'asis'}
# Plot
ggplot(data = df) +
    aes(x = 'Data',
        y = cd4_cells.ul) +
    geom_sina() +
    labs(subtitle = 'CD4: density plot',
         y = 'CD4 T-cell count (cells/uL)') +
    theme(axis.title.x = element_blank(),
          axis.text.x = element_blank())

# Numeric summary
df %>% 
    select(cd4_cells.ul) %>% 
    skim() %>% 
    skimr::kable(caption = 'CD4 T-cell count: summary statistics')
```

## Viral load

```{r viral, results = 'asis'}
# Plot
ggplot(data = df) +
    aes(x = 'Data',
        y = viral_load_cp.ml) +
    geom_sina() +
    scale_y_log10() +
    labs(subtitle = 'Viral load: density plot',
         y = 'log10(Viral load (copies/mL))') +
    theme(axis.title.x = element_blank(),
          axis.text.x = element_blank())

# Numeric summary
df %>% 
    select(viral_load_cp.ml) %>% 
    skim() %>% 
    skimr::kable(caption = 'Viral load: summary statistics')
```

## Perception of health (baseline)

```{r qol, results = 'asis'}
# Plot
ggplot(data = df) +
    aes(x = 'Data',
        y = general_health) +
    geom_sina() +
    scale_y_continuous(limits = c(0, 5)) +
    labs(subtitle = 'General health: density plot',
         y = 'General health') +
    theme(axis.title.x = element_blank(),
          axis.text.x = element_blank())

# Numeric summary
df %>% 
    select(general_health) %>% 
    skim() %>% 
    skimr::kable(caption = 'General health: summary statistics')

# Mode
xtabs(~general_health, data = df) %>% 
    knitr::kable(caption = 'General health: modal distribution')
```

----

# Session information

```{r sessioninfo}
sessionInfo()
```