---
title: "Script 4"
subtitle: "Pain intensity"
author: "Peter Kamerman"
date: "`r format(Sys.Date(), '%d %B %Y')`"
geometry: margin=15mm
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(knitr)
library(skimr)
library(boot)
```

----

# Analysis notes

## Definitions of missingness

Data were regarded as **missing** when _pain in the last week_ data were not present for one or more of weeks 0, 12, 24, 36, 48. Data also were classified as **missing** when there were inconsistencies in the data across the variables collected within a week.

## Definition of data inconsistencies

Pain was defined as _pain in the last week_  being 'Yes', and _pain at its worst_ being > 0. These two measurements were then the "gatekeeper" measurements, such that the two measurements both had to be positive ('Yes' and '> 0', respectively) in order for there to be any entries for _site of pain_ and _site of worst pain_. Were the data were inconsistent (e.g., when there was no _pain in the last week_ and _pain at its worst_ = 0, but there were entries for _site of pain_ and _site of worst pain_), then the _site of pain_ and _site of worst pain_ entries were marked as **inconsistent**. 

Data also were considered **inconsistent** when _pain in the last week_ = 'Yes', but _site of worst pain_ = 'None'. 

Lastly, data were considered **inconsistent** when _site of worst pain_ was not listed as one of the pain locations for a given measurement week.

----

# Import data

```{r import}
df <- read_rds('data-cleaned/data-ADVANCE.rds') %>% 
    select(ranid, interval_name, pain_in_the_last_week, 
           any_missing, pain_worst)
```

# First look 

```{r inspect}
head(df)
glimpse(df)
```

# Basic clean data

```{r clean}
# Extract those participants with no missing data and who had pain
df %<>%
  filter(any_missing == 'No') %>% 
  select(-any_missing) %>% 
  filter(pain_in_the_last_week == 'Yes')
  
```

# Quick tabulation

## Analysis data set for the period 0 to 48 weeks

```{r quick_tab}
# Tabulate data
xtabs(~interval_name, data = df)
```

----

# Tabulate data

## 7-number summary of pain intensity at each visit

```{r pain_intensity_summary}
df %>% 
  select(interval_name, pain_worst) %>% 
  group_by(interval_name) %>% 
  skim() %>% 
  yank('numeric') %>% 
  select(-complete_rate, -hist) %>% 
  kable(caption = '7-number summary of pain intensity (11-point NRS) by time point')
```

## Mean (95%CI) of pain intensity at each visit

```{r pain_intensity_mean}
# Bootstrap function
boot_mean <- function(d, i){
  data <- d[i, ]
  mn <- mean(data$pain_worst, na.rm = TRUE)
  mn
}

# Set seed
set.seed(2019)

# Bootstrap and tabulate data
df %>% 
  select(interval_name, pain_worst) %>% 
  group_by(interval_name) %>% 
  nest() %>% 
  mutate(boot_ = map(.x = data,
                     ~ boot(data = .x, 
                            statistic = boot_mean,
                            R = 5000,
                            stype = 'i'))) %>% 
  mutate(boot_ci = map(.x = boot_,
                       ~ boot.ci(.x, 
                                 type = 'basic'))) %>% 
  mutate(mean = map(.x = boot_ci,
                    ~ round(.$t0, 1)),
         lower_ci95 = map(.x = boot_ci,
                          ~ round(.$basic[[4]], 1)),
         upper_ci95 = map(.x = boot_ci,
                          ~ round(.$basic[[5]], 1))) %>%
  select(interval_name, mean, lower_ci95, upper_ci95) %>% 
  unnest(cols = c(mean, lower_ci95, upper_ci95)) %>% 
  arrange(interval_name) %>% 
  kable(caption = 'Mean (95% CI) pain intensity (11-point NRS) by time point')
```

## Median (95%CI) of pain intensity at each visit

```{r pain_intensity_median}
# Bootstrap function
boot_median <- function(d, i){
  data <- d[i, ]
  mdn <- median(data$pain_worst, na.rm = TRUE)
  mdn
}

# Set seed
set.seed(2019)

# Bootstrap data
df %>% 
  select(interval_name, pain_worst) %>% 
  group_by(interval_name) %>% 
  nest() %>% 
  mutate(boot_ = map(.x = data,
                     ~ boot(data = .x, 
                            statistic = boot_median,
                            R = 5000,
                            stype = 'i'))) %>% 
  mutate(boot_ci = map(.x = boot_,
                       ~ boot.ci(.x, 
                                 type = 'basic'))) %>% 
  mutate(median = map(.x = boot_ci,
                      ~ round(.$t0, 1)),
         lower_ci95 = map(.x = boot_ci,
                          ~ round(.$basic[[4]], 1)),
         upper_ci95 = map(.x = boot_ci,
                          ~ round(.$basic[[5]], 1))) %>%
  select(interval_name, median, lower_ci95, upper_ci95) %>% 
  unnest(cols = c(median, lower_ci95, upper_ci95)) %>% 
  arrange(interval_name) %>% 
  kable(caption = 'Median (95% CI) pain intensity (11-point NRS) by time point')
```

----

# Session information

```{r session_info}
sessionInfo()
```