---
title: "Script 3b"
subtitle: "Pain progression: individual data"
author: "Peter Kamerman"
date: "`r format(Sys.Date(), '%d %B %Y')`"
geometry: margin=15mm
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(ggthemes)
library(patchwork)
library(knitr)

# Set figures directory
if(!dir.exists('./figures')) {
    dir.create('./figures/')
}

if(!dir.exists('./figures/script-3b')) {
    dir.create('./figures/script-3b/')
}

# knitr options
opts_chunk$set(warning = FALSE,
               message = FALSE,
               fig.path = './figures/script-3b/')
```

----

# Analysis notes

## Definitions of missingness

Data were regarded as **missing** when _pain in the last week_ data were not present for one or more of weeks 0, 12, 24, 36, 48. Data also were classified as **missing** when there were inconsistencies in the data across the variables collected within a week.

## Definition of data inconsistencies

Pain was defined as _pain in the last week_  being 'Yes', and _pain at its worst_ being > 0. These two measurements were then the "gatekeeper" measurements, such that the two measurements both had to be positive ('Yes' and '> 0', respectively) in order for there to be any entries for _site of pain_ and _site of worst pain_. Were the data were inconsistent (e.g., when there was no _pain in the last week_ and _pain at its worst_ = 0, but there were entries for _site of pain_ and _site of worst pain_), then the _site of pain_ and _site of worst pain_ entries were marked as **inconsistent**. 

Data also were considered **inconsistent** when _pain in the last week_ = 'Yes', but _site of worst pain_ = 'None'. 

Lastly, data were considered **inconsistent** when _site of worst pain_ was not listed as one of the pain locations for a given measurement week.

For analysis purposes, missing data in the _site of pain_ columns were changed to **'No'** (pain not present in the site). This approach was conservative, but we believed that the approach would have the least effect on the outcome, while still retaining as many participants as possible.

----

# Import data

```{r import}
df <- read_rds('data-cleaned/data-ADVANCE.rds') %>% 
    select(ranid, interval_name, pain_in_the_last_week, 
           any_missing, interval_numeric)
```

# Quick look 

```{r inspect}
head(df)
glimpse(df)
```

# Basic clean

```{r clean}
# Clean and process data
df %<>% 
    filter(any_missing == 'No') %>% 
    select(-any_missing) %>% 
    rename(time_weeks = interval_numeric)
```

# Quick tabulation

## Analysis data set for the period 0 to 48 weeks

```{r quick_tab}
# Tabulate data
xtabs(~interval_name, data = df)
```

----

# Pain per visit:

## Plot summary data vs participant-level data

```{r pain_per_visit, fig.height = 6}
# Generate participant-level plot
plot_individual <- df %>% 
    group_by(interval_name) %>% 
    mutate(id = row_number()) %>% 
    ggplot(.) +
    aes(x = factor(time_weeks),
        y = id) +
    geom_tile(aes(fill = pain_in_the_last_week),
              width = 1) +
    scale_fill_tableau(name = 'Pain in the last week: ') +
    labs(x = 'Time (weeks)',
         y = 'Number of participants') +
    theme_minimal(base_size = 16) +
    theme(legend.position = 'top',
          panel.grid.minor = element_blank()); plot_individual
```

## Tabulate pain progression patterns

```{r pain_per_visit2}
# Generate the pain sequences 
df_sequence <- df %>% 
    select(ranid, interval_name, pain_in_the_last_week) %>% 
    mutate(pain_in_the_last_week = as.character(pain_in_the_last_week)) %>% 
    pivot_wider(names_from = interval_name,
                values_from = pain_in_the_last_week) %>% 
    unite(col = 'sequence', -ranid, sep = ' ') %>% 
    mutate(any_pain = str_detect(sequence, pattern = 'Yes'))

# x-tabulate the sequences
df_xtab <- as.data.frame(xtabs(~sequence, data = df_sequence)) %>% 
    arrange(desc(Freq)) %>% 
    rename(frequency = Freq) %>% 
    mutate(percent = round(100 * frequency / sum(frequency), 2))

# Print table
kable(df_xtab, 
      caption = 'Pain in the last week for weeks 0, 12, 24, 36 and 48')
```

## Number of sequences with 'yes' in series

```{r pain_per_visit3}
# Extract sequences
df_yes <- df_sequence %>%
    mutate(yes_2 = str_detect(sequence, pattern = 'Yes Yes')) %>% 
    mutate(yes_3 = str_detect(sequence, pattern = 'Yes Yes Yes')) %>% 
    mutate(yes_4 = str_detect(sequence, pattern = 'Yes Yes Yes Yes')) %>% 
    mutate(yes_5 = str_detect(sequence, pattern = 'Yes Yes Yes Yes Yes')) 

# Create filters
vec_filter_2yes <- df_yes %>% 
    filter(yes_2 == TRUE) %>% 
    .$ranid

vec_filter_3yes <- df_yes %>% 
    filter(yes_3 == TRUE) %>% 
    .$ranid

vec_filter_4yes <- df_yes %>% 
    filter(yes_4 == TRUE) %>% 
    .$ranid

vec_filter_5yes <- df_yes %>% 
    filter(yes_5 == TRUE) %>% 
    .$ranid

# Extract data
df_2yes <- df_yes %>% 
    filter(!ranid %in% vec_filter_5yes) %>% 
    filter(!ranid %in% vec_filter_4yes) %>% 
    filter(!ranid %in% vec_filter_3yes) %>% 
    filter(ranid %in% vec_filter_2yes)

df_3yes <- df_yes %>% 
    filter(!ranid %in% vec_filter_5yes) %>% 
    filter(!ranid %in% vec_filter_4yes) %>% 
    filter(ranid %in% vec_filter_3yes) 

df_4yes <- df_yes %>% 
    filter(!ranid %in% vec_filter_5yes) %>% 
    filter(ranid %in% vec_filter_4yes)

df_5yes <- df_yes %>% 
    filter(ranid %in% vec_filter_5yes)
    
# Sequences with 2 'yes' in series ONLY
kable(data.frame('type' = c('Sequence count', 'Percent of total sequences'),
                  'value' = c(round(sum(df_2yes$yes_2)), 
                              round(100 * (sum(df_2yes$yes_2) / 
                                               sum(df_xtab$frequency)), 2))),
      caption = "Sequences with 2 'yes' (pain present) in series")

# Sequences with 3 'yes' (pain present) in series ONLY
kable(data.frame('type' = c('Sequence count', 'Percent of total sequences'),
                 'value' = c(round(sum(df_3yes$yes_3)), 
                             round(100 * (sum(df_3yes$yes_3) /
                                              sum(df_xtab$frequency)), 2))),
      caption = "Sequences with 3 'yes' (pain present) in series")

# Sequences with 4 'yes' (pain present) in series ONLY
kable(data.frame('type' = c('Sequence count', 'Percent of total sequences'),
                 'value' = c(round(sum(df_4yes$yes_4)), 
                             round(100 * (sum(df_4yes$yes_4) / 
                                              sum(df_xtab$frequency)), 2))),
      caption = "Sequences with at least 4 'yes' (pain present) in series")

# Sequences with at least 5 'yes' (pain present) in series
kable(data.frame('type' = c('Sequence count', 'Percent of total sequences'),
                 'value' = c(round(sum(df_5yes$yes_5)), 
                             round(100 * (sum(df_5yes$yes_5) / 
                                              sum(df_xtab$frequency)), 2))),
      caption = "Sequences with at least 5 'yes' (pain present) in series")

# Number of participants with isolated pain
787 - sum(c(393,79, 20, 4, 1))

# Proportion of participants with isolated pain
(787 - sum(c(393,79, 20, 4, 1)))/787
```

----

# Session information

```{r session_info}
sessionInfo()
```
