---
title: "Script 2c"
subtitle: "Descriptive stats by pain status"
author: "Peter Kamerman"
date: "`r format(Sys.Date(), '%d %B %Y')`"
geometry: margin=15mm
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(ggthemes)
library(patchwork)
library(knitr)

# Set figures directory
if(!dir.exists('./figures')) {
    dir.create('./figures/')
}

if(!dir.exists('./figures/script-2c')) {
    dir.create('./figures/script-2c/')
}

# ggplot theme
theme_set(new = theme_bw(base_size = 16))

# knitr options
opts_chunk$set(warning = FALSE,
               message = FALSE, 
               fig.path = './figures/script-2c/')
```

----

# Analysis notes

Pain was defined as _pain in the last week_  being 'Yes', and _pain at its worst_ being > 0.

These two measurements were then the "gatekeeper" measurements, such that the two measurements both had to be positive ('Yes' and '> 0', respectively) in order for there to be any entries for _site of pain_ and _site of worst pain_. Were the data were incongruent (e.g., when there was no _pain in the last week_ and _pain at its worst_ = 0, but there were entries for _site of pain_ and _site of worst pain_), then the _site of pain_ and _site of worst pain_ entries were marked as **incongruent**. 

Data also were considered **incongruent** when _pain in the last week_ = 'Yes', but _site of worst pain_ = 'None'. 

Lastly, data were considered **incongruent** when _site of worst pain_ was not listed as one of the pain locations for a given measurement week.

For analysis purposes, missing data in the _site of pain_ columns were changed to **'No'** (pain not present in the site). This approach was conservative, but we believed that the approach would have the least effect on the outcome, while still retaining as many participants as possible.

----

# Import data

```{r import}
df <- read_rds('data-cleaned/data-ADVANCE.rds') %>% 
    select(ranid, interval_name, pain_in_the_last_week, 
           cd4_cells.ul, viral_load_cp.ml, general_health,
           any_missing, interval_numeric)
```

# First look 

```{r inspect}
head(df)
glimpse(df)
```

# Basic clean

```{r clean}
# Clean and process data
df %<>% 
    filter(any_missing == 'No') %>% 
    select(-any_missing)
```

# Quick tabulation

## Analysis data set for the period 0 to 48 weeks

```{r quick_tab}
# Tabulate data
xtabs(~interval_name, data = df)
```

----

# Analysis

## Prepare summary data for tabulation

```{r prepare}
# Pain in the last week
df_pain <- as.data.frame(xtabs(~interval_name + pain_in_the_last_week, 
                               data = df)) %>% 
    rename(count = Freq) %>% 
    group_by(interval_name) %>% 
    mutate(total = sum(count)) %>% 
    mutate(proportion = round(count / total, 3)) %>% 
    filter(pain_in_the_last_week == 'Yes') 

# CD4 (by pain status)
df_cd4 <- df %>% 
    group_by(interval_name) %>% 
    summarise(missing = sum(is.na(cd4_cells.ul)),
              median = median(cd4_cells.ul, na.rm = TRUE),
              Q25 = quantile(cd4_cells.ul, probs = 0.25, na.rm = TRUE),
              Q75 = quantile(cd4_cells.ul, probs = 0.75, na.rm = TRUE),
              min = min(cd4_cells.ul, na.rm = TRUE),
              max = max(cd4_cells.ul, na.rm = TRUE)) 

df_cd4 <- df_cd4[c(1, 3, 5), ] # weeks 0, 12, 48

# Viral load (by pain status)
df_vl <- df %>% 
    group_by(interval_name, pain_in_the_last_week) %>% 
    mutate(viral_load_cp.ml = ifelse(viral_load_cp.ml < 50,
                                     yes = 50,
                                     no = viral_load_cp.ml)) %>% 
    summarise(missing = sum(is.na(viral_load_cp.ml)),
              median = median(viral_load_cp.ml, na.rm = TRUE),
              Q25 = quantile(viral_load_cp.ml, probs = 0.25, na.rm = TRUE),
              Q75 = quantile(viral_load_cp.ml, probs = 0.75, na.rm = TRUE),
              min = min(viral_load_cp.ml, na.rm = TRUE),
              max = max(viral_load_cp.ml, na.rm = TRUE)) 

# general health (by pain status)
df_gh <- df %>% 
    group_by(interval_name, pain_in_the_last_week) %>% 
    summarise(missing = sum(is.na(general_health)),
              median = median(general_health, na.rm = TRUE),
              Q25 = quantile(general_health, probs = 0.25, na.rm = TRUE),
              Q75 = quantile(general_health, probs = 0.75, na.rm = TRUE),
              min = min(general_health, na.rm = TRUE),
              max = max(general_health, na.rm = TRUE)) 
```

## Pain proportion

```{r pain_proportion}
# Pain
df_pain %>% 
  kable(caption = 'Proportion with pain in the last week')
```

## CD4

```{r cd4_tabulate}
# Tabulate CD4 (by pain status)
df_cd4 %>% 
  kable(caption = '5-number summary of CD4 T-cell count (cells/ul) by pain status')
```

```{r cd4_plot, fig.height = 6}
# Plot CD4 (by pain status)
p_cd4 <- df %>% 
    select(interval_name, interval_numeric, 
           pain_in_the_last_week, cd4_cells.ul) %>% 
    mutate(cd4_cells.ul = ifelse(interval_numeric == 12 | interval_numeric == 36,
                                 yes = NA,
                                 no = cd4_cells.ul)) %>% 
    ggplot(data = .) +
    aes(y = cd4_cells.ul, 
        x = interval_name,
        fill = pain_in_the_last_week) +
    geom_boxplot(key_glyph = "rect") +
    labs(title = 'CD4 T-cell count',
         y = expression('CD4 count (cells/mm'^3*')'),
         x = 'Weeks') +
    scale_x_discrete(labels = c('0', '12', '24', '36', '48')) +
    scale_fill_tableau(name = 'Pain in the last week') +
    theme(legend.position = 'top',
          panel.grid = element_blank()); p_cd4
```

## Viral load

```{r vl_tabulate}
# Tabulate viral load (by pain status)
df_vl %>% 
  kable(caption = '5-number summary of viral load (copies/ml) by pain status')
```

```{r vl_plot, fig.height = 6}
# Plot viral load (by pain status)
p_vl <- df %>% 
    select(interval_name, pain_in_the_last_week, viral_load_cp.ml) %>% 
    ggplot(data = .) +
    aes(y = viral_load_cp.ml, 
        x = interval_name,
        fill = pain_in_the_last_week) +
    geom_boxplot(key_glyph = "rect") +
    labs(title = 'HIV-1 RNA viral load ',
         y = expression('Viral load [log'[10]*'(copies/ml)]'),
         x = 'Weeks') +
    scale_x_discrete(labels = c('0', '12', '24', '36', '48')) +
    scale_y_log10() +
    scale_fill_tableau(name = 'Pain: ') +
    theme(legend.position = 'top',
          panel.grid = element_blank()); p_vl
```

## General health

```{r gh_tabulate}
# Tabulate general health (by pain status)
df_gh %>% 
  kable(caption = '5-number summary of general health (0-5 rating scale) by pain status')
```

```{r gh_plot, fig.height = 6.5}
# Plot general health (by pain status)
p_gh <- df %>% 
    select(interval_name, pain_in_the_last_week, general_health) %>% 
    ggplot(data = .) +
    aes(y = general_health, 
        x = interval_name,
        fill = pain_in_the_last_week) +
    geom_boxplot(key_glyph = "rect") +
    labs(title = 'General health',
         y = 'General health (0-5 rating scale)',
         x = 'Weeks') +
    scale_x_discrete(labels = c('0', '12', '24', '36', '48')) +
    scale_fill_tableau(name = 'Pain: ') +
    theme(legend.position = 'top',
          panel.grid = element_blank()); p_gh
```

----

# Session information

```{r session_info}
sessionInfo()
```