---
title: "Script 3a"
subtitle: "Pain progression: group data"
author: "Peter Kamerman"
date: "`r format(Sys.Date(), '%d %B %Y')`"
geometry: margin=15mm
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(ggalluvial)
library(ggthemes)
library(boot)
library(patchwork)
library(knitr)

# Set figures directory
if(!dir.exists('./figures')) {
    dir.create('./figures/')
}

if(!dir.exists('./figures/script-3a')) {
    dir.create('./figures/script-3a/')
}

# knitr options
opts_chunk$set(warning = FALSE,
               message = FALSE,
               fig.path = './figures/script-3a/')
```

----

# Analysis notes

## Definitions of missingness

Data were regarded as **missing** when _pain in the last week_ data were not present for one or more of weeks 0, 12, 24, 36, 48. Data also were classified as **missing** when there were inconsistencies in the data across the variables collected within a week.

## Definition of data inconsistencies

Pain was defined as _pain in the last week_  being 'Yes', and _pain at its worst_ being > 0. These two measurements were then the "gatekeeper" measurements, such that the two measurements both had to be positive ('Yes' and '> 0', respectively) in order for there to be any entries for _site of pain_ and _site of worst pain_. Were the data were inconsistent (e.g., when there was no _pain in the last week_ and _pain at its worst_ = 0, but there were entries for _site of pain_ and _site of worst pain_), then the _site of pain_ and _site of worst pain_ entries were marked as **inconsistent**. 

Data also were considered **inconsistent** when _pain in the last week_ = 'Yes', but _site of worst pain_ = 'None'. 

Lastly, data were considered **inconsistent** when _site of worst pain_ was not listed as one of the pain locations for a given measurement week.

For analysis purposes, missing data in the _site of pain_ columns were changed to **'No'** (pain not present in the site). This approach was conservative, but we believed that the approach would have the least effect on the outcome, while still retaining as many participants as possible.

----

# Import data

```{r import}
df <- read_rds('data-cleaned/data-ADVANCE.rds') %>% 
    select(ranid, interval_name, pain_in_the_last_week, 
           any_missing)
```

# Quick look 

```{r inspect}
head(df)
glimpse(df)
```

# Basic clean

```{r clean}
# Clean and process data
df %<>% 
    filter(any_missing == 'No') %>% 
    select(-any_missing) %>% 
    # Add enrolment marker
    pivot_wider(names_from = interval_name,
                values_from = pain_in_the_last_week) %>%
    mutate(pain_at_enrolment = ifelse(`0 weeks` == 'Yes',
                                      yes = 'Yes',
                                      no = 'No'), 
           pain_at_enrolment = factor(pain_at_enrolment)) %>%
    pivot_longer(cols = ends_with(' weeks'), 
                 names_to = 'interval_name',
                 values_to = 'pain_in_the_last_week') %>% 
    # Add numeric time
    mutate(time_weeks = str_extract(interval_name,
                                    pattern = '[0-9]?[0-9]'),
           time_weeks = as.numeric(time_weeks))
```

# Quick tabulation

## Analysis data set for the period 0 to 48 weeks

```{r quick_tab}
# Tabulate data
xtabs(~interval_name, data = df)
```

----

# Analysis

## Prepare data

Add a dummy frequency column for sankey diagram.

```{r prepare}
# Add dummy freq
df_sankey <- df %>% 
    mutate(freq = 1)
```

## Numeric summary: All

```{r quick2}
# Tabulate data
tab_prop1 <- as.data.frame(xtabs(~time_weeks + pain_in_the_last_week, data = df)) %>% 
    pivot_wider(names_from = pain_in_the_last_week,
                values_from = Freq,
                names_prefix = 'pain_') %>% 
    mutate(total_cases = rowSums(.[2:3])) %>% 
    mutate(point_estimate = pain_Yes / total_cases) %>% 
    select(time_weeks, total_cases, everything()) %>% 
    mutate(time_weeks = as.numeric(as.character(time_weeks)))

# Calculate 95%CI
# Boot function
booted <- function(d, i, prop_factor = 'Yes'){
    data <- d[i, ]
    data2 <- data$pain_in_the_last_week
    prop <- mean(data2 == prop_factor)
    prop
}

# Set the seed
set.seed(2019)

# Bootstrap values
tab_prop2 <- df %>% 
    group_by(time_weeks) %>% 
    nest() %>% 
    mutate(data_boot = map(.x = data,
                           ~ boot(data = .x, 
                                  R = 5000, 
                                  statistic = booted, 
                                  stype = 'i'))) %>% 
    mutate(data_ci = map(.x = data_boot,
                         ~ boot.ci(.x,
                                   type = 'basic'))) %>% 
    mutate(data_point = map(.x = data_boot,
                            ~ .x$t0),
           data_ci.lower = map(.x = data_ci,
                               ~ .x$basic[[4]]),
           data_ci.upper = map(.x = data_ci,
                               ~ .x$basic[[5]])) 

# Extract bootstrapped data
tab_prop2 %<>% 
    select(time_weeks, data_point, data_ci.lower, data_ci.upper) %>% 
    unnest(cols = c('data_point', 'data_ci.lower', 'data_ci.upper')) %>% 
    rename(point_estimate = data_point,
           lower_CI = data_ci.lower,
           upper_CI = data_ci.upper)
    
# Join tab_prop1 and tab_prop2
tab_prop3 <- tab_prop1 %>% 
    left_join(tab_prop2) %>% 
    mutate(time_weeks = factor(time_weeks))
    
# Tabulate
kable(tab_prop3, 
      caption = 'Estimate and 95% CI of the proportion with pain by week')
```

## Point plot with 95% CI: All

```{r plot_95}
# Plot bootstrapped data
ggplot(data = tab_prop3) +
    aes(x = as.numeric(as.character(time_weeks)),
        y = point_estimate,
        ymin = lower_CI,
        ymax = upper_CI) +
    geom_errorbar(size = 1) +
    geom_point(size = 8) +
    scale_y_continuous(limits = c(0, 0.3)) +
    scale_x_continuous(breaks = c(0, 12, 24, 36, 48)) +
    labs(subtitle = 'Estimate and 95% CI of the proportion with pain',
         x = 'Weeks',
         y = 'Proportion')
```

## Sankey plot 1: All

```{r sankey_plot1, fig.width = 7, fig.height = 7}
# Breaks
n <- length(unique(df$ranid))

# Generate plot for publication
sankey_plot1 <- ggplot(data = df_sankey) +
    aes(x = factor(time_weeks),
        stratum = pain_in_the_last_week, 
        alluvium = ranid,
        y = freq,
        fill = pain_in_the_last_week,
        label = pain_in_the_last_week) +
    geom_flow() +
    geom_stratum(width = 0.35) +
    scale_fill_tableau(name = 'Pain in the last week') +
    scale_y_continuous(breaks = c(n * 0, n * 0.2, n * 0.4, n * 0.6, n * 0.8, n),
                       labels = c('0.0', '0.2', '0.4', '0.6', '0.8', '1.0')) +
    scale_x_discrete(expand = c(0.06, 0)) +
    labs(x = 'Time (weeks)',
         y = 'Proportion of participants') +
    theme_minimal(base_size = 20) +
    theme(legend.position = 'top',
          panel.grid.minor = element_blank())

# Save plot
ggsave(filename = 'figures/figure-3.png', sankey_plot1, 
       width = 10.2, height = 7.72)

# Generate plot for knitr output
ggplot(data = df_sankey) +
    aes(x = factor(time_weeks),
        stratum = pain_in_the_last_week, 
        alluvium = ranid,
        y = freq,
        fill = pain_in_the_last_week,
        label = pain_in_the_last_week) +
    geom_flow() +
    geom_stratum(width = 0.35) +
    scale_fill_tableau(name = 'Pain in the last week') +
    scale_y_continuous(breaks = c(n * 0, n * 0.2, n * 0.4, n * 0.6, n * 0.8, n),
                       labels = c('0.0', '0.2', '0.4', '0.6', '0.8', '1.0')) +
    scale_x_discrete(expand = c(0.06, 0)) +
    labs(x = 'Time (weeks)',
         y = 'Proportion of participants') +
    theme_minimal(base_size = 16) +
    theme(legend.position = 'top',
          panel.grid.minor = element_blank())
```

## Sankey plot 2: Pain at enrolment

```{r sankey_plot2, fig.width = 7, fig.height = 7}
# Breaks
n2 <- length(unique(df$ranid[df$pain_at_enrolment == 'Yes']))
    
# Generate plot
sankey_plot2 <- df_sankey %>% 
    select(-interval_name) %>% 
    filter(pain_at_enrolment == 'Yes') %>% 
    ggplot(data = .) +
    aes(x = factor(time_weeks),
        stratum = pain_in_the_last_week, 
        alluvium = ranid,
        y = freq,
        fill = pain_in_the_last_week,
        label = pain_in_the_last_week) +
    geom_flow() +
    geom_stratum() +
    scale_fill_tableau(name = 'Pain in the last week') +
    scale_y_continuous(breaks = c(n2 * 0, n2 * 0.2, n2 * 0.4, n2 * 0.6, n2 * 0.8, n2),
                       labels = c('0.0', '0.2', '0.4', '0.6', '0.8', '1.0')) +
    labs(title = 'Participants with pain at enrolment',
         subtitle = str_glue("(n = {length(unique(df$ranid[df$pain_at_enrolment == 'Yes']))})"),
         x = 'Time (weeks)',
         y = 'Proportion of participants') +
    theme_minimal(base_size = 16) +
    theme(legend.position = 'top'); sankey_plot2 
```

## Sankey plot 3: No pain at enrolment

```{r sankey_plot3, fig.width = 7, fig.height = 7}
# Breaks
n3 <- length(unique(df$ranid[df$pain_at_enrolment == 'No']))
    
# Generate plot
sankey_plot3 <- df_sankey %>% 
    select(-interval_name) %>% 
    filter(pain_at_enrolment == 'No') %>% 
    ggplot(data = .) +
    aes(x = factor(time_weeks),
        stratum = pain_in_the_last_week, 
        alluvium = ranid,
        y = freq,
        fill = pain_in_the_last_week,
        label = pain_in_the_last_week) +
    geom_flow() +
    geom_stratum() +
    scale_fill_tableau(name = 'Pain in the last week') +
    scale_y_continuous(breaks = c(n3 * 0, n3 * 0.2, n3 * 0.4, n3 * 0.6, n3 * 0.8, n3),
                       labels = c('0.0', '0.2', '0.4', '0.6', '0.8', '1.0')) +
    labs(title = 'Participants with no pain at enrolment',
         subtitle = str_glue("(n = {length(unique(df$ranid[df$pain_at_enrolment == 'No']))})"),
         x = 'Time (weeks)',
         y = 'Proportion of participants') +
    theme_minimal(base_size = 16) +
    theme(legend.position = 'top'); sankey_plot3
```

----

# Number of people transitioning between pain states at each time period

## Separate time points

```{r transition_1}
# Week 0 to 12
t0.12 <- df %>% 
    filter(time_weeks %in% c(0, 12)) %>% 
    select(-interval_name, -pain_at_enrolment)

# Week 12 to 24
t12.24 <- df %>% 
    filter(time_weeks %in% c(12, 24)) %>% 
    select(-interval_name, -pain_at_enrolment)

# Week 24 to 36
t24.36 <- df %>% 
    filter(time_weeks %in% c(24, 36)) %>% 
    select(-interval_name, -pain_at_enrolment)

# Week 36 to 48
t36.48 <- df %>% 
    filter(time_weeks %in% c(36, 48)) %>% 
    select(-interval_name, -pain_at_enrolment)
```

## Calculate percent transitioning pain state

```{r transition_2}
# Week 0 to 12
t0.12 %>% 
    pivot_wider(names_from = time_weeks,
                values_from = pain_in_the_last_week) %>% 
    mutate_if(is.factor, as.character) %>% 
    mutate(pain_transition = paste0(`0`, `12`)) %>% 
    filter(!pain_transition %in% c('YesYes', 'NoNo')) %>% 
    mutate(pain_transition = ifelse(pain_transition == 'YesNo',
                                    yes = 'Pain to no pain',
                                    no = 'No pain to pain')) %>% 
    group_by(pain_transition) %>% 
    summarise(count = n()) %>% 
    mutate(prop = count / length(unique(df$ranid)),
           percent = 100 * round(prop, 3)) %>% 
    kable(caption = 'Pain transitions: week 0 to 12')

# Week 12 to 24
t12.24 %>% 
    pivot_wider(names_from = time_weeks,
                values_from = pain_in_the_last_week) %>% 
    mutate_if(is.factor, as.character) %>% 
    mutate(pain_transition = paste0(`12`, `24`)) %>% 
    filter(!pain_transition %in% c('YesYes', 'NoNo')) %>% 
    mutate(pain_transition = ifelse(pain_transition == 'YesNo',
                                    yes = 'Pain to no pain',
                                    no = 'No pain to pain')) %>% 
    group_by(pain_transition) %>% 
    summarise(count = n()) %>% 
    mutate(prop = count / length(unique(df$ranid)),
           percent = 100 * round(prop, 3)) %>% 
    kable(caption = 'Pain transitions: week 12 to 24')

# Week 24 to 36
t24.36 %>% 
    pivot_wider(names_from = time_weeks,
                values_from = pain_in_the_last_week) %>% 
    mutate_if(is.factor, as.character) %>% 
    mutate(pain_transition = paste0(`24`, `36`)) %>% 
    filter(!pain_transition %in% c('YesYes', 'NoNo')) %>% 
    mutate(pain_transition = ifelse(pain_transition == 'YesNo',
                                    yes = 'Pain to no pain',
                                    no = 'No pain to pain')) %>% 
    group_by(pain_transition) %>% 
    summarise(count = n()) %>% 
    mutate(prop = count / length(unique(df$ranid)),
           percent = 100 * round(prop, 3)) %>% 
    kable(caption = 'Pain transitions: week 24 to 36')

# Week 36 to 48
t36.48 %>% 
    pivot_wider(names_from = time_weeks,
                values_from = pain_in_the_last_week) %>% 
    mutate_if(is.factor, as.character) %>% 
    mutate(pain_transition = paste0(`36`, `48`)) %>% 
    filter(!pain_transition %in% c('YesYes', 'NoNo')) %>% 
    mutate(pain_transition = ifelse(pain_transition == 'YesNo',
                                    yes = 'Pain to no pain',
                                    no = 'No pain to pain')) %>% 
    group_by(pain_transition) %>% 
    summarise(count = n()) %>% 
    mutate(prop = count / length(unique(df$ranid)),
           percent = 100 * round(prop, 3)) %>% 
    kable(caption = 'Pain transitions: week 36 to 38')
```

----

# Session information

```{r session_info}
sessionInfo()
```