---
title: "Supplement 2"
subtitle: "Statistics at each time period"
author: "Peter Kamerman"
date: "`r format(Sys.Date(), '%d %B %Y')`"
geometry: margin=15mm
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(skimr)
library(knitr)
library(broom)

# Set figures directory
if(!dir.exists('./figures')) {
    dir.create('./figures/')
}

if(!dir.exists('./figures/supplement-2')) {
    dir.create('./figures/supplement-2/')
}

# ggplot theme
theme_set(new = theme_bw(base_size = 16))

# knitr options
opts_chunk$set(warning = FALSE,
               message = FALSE, 
               fig.path = './figures/supplement-2/')
```

----

# Objective 

To describe the pain characteristics (analysis cohort and stratified by data missingness), demographic characteristics (analysis cohort only), and disease status (analysis cohort only) at each time point.

# Analysis notes

## Definitions of missingness

Data were regarded as **missing** when _pain in the last week_ data were not present for one or more of weeks 0, 12, 24, 36, 48. Data also were classified as **missing** when there were inconsistencies in the data across the variables collected within a week.

## Definition of data inconsistencies

Pain was defined as _pain in the last week_  being 'Yes', and _pain at its worst_ being > 0. These two measurements were then the "gatekeeper" measurements, such that the two measurements both had to be positive ('Yes' and '> 0', respectively) in order for there to be any entries for _site of pain_ and _site of worst pain_. Were the data were inconsistent (e.g., when there was no _pain in the last week_ and _pain at its worst_ = 0, but there were entries for _site of pain_ and _site of worst pain_), then the _site of pain_ and _site of worst pain_ entries were marked as **inconsistent**. 

Data also were considered **inconsistent** when _pain in the last week_ = 'Yes', but _site of worst pain_ = 'None'. 

Lastly, data were considered **inconsistent** when _site of worst pain_ was not listed as one of the pain locations for a given measurement week.

For analysis purposes, missing data in the _site of pain_ columns were changed to **'No'** (pain not present in the site). This approach was conservative, but we believed that the approach would have the least effect on the outcome, while still retaining as many participants as possible.

----

# Import data

```{r import}
df <- read_rds('data-cleaned/data-ADVANCE.rds') %>% 
    select(ranid, interval_name, group, pain_in_the_last_week, pain_worst,
           cd4_cells.ul, viral_load_cp.ml,
           general_health, any_missing, interval_numeric)
```

# First look 

```{r inspect}
head(df)
glimpse(df)
```

# Basic clean

```{r clean}
# Clean and process data
df_pain <- df %>%  
    select(ranid, any_missing) %>% 
    distinct()

pain_nested <- df %>% 
    select(ranid, interval_name, pain_worst, any_missing) %>% 
    group_by(interval_name) %>% 
    nest() 

df %<>% 
    filter(any_missing == 'No') %>% 
    select(-any_missing)
```

# Quick tabulation

## Analysis data set for the period 0 to 48 weeks

```{r quick_tab}
# Tabulate data
xtabs(~interval_name, data = df)
```

----

# Analysis

## Number of participants with/without complete pain data

```{r missing_count}
df_pain %>% 
    group_by(any_missing) %>% 
    summarise(count = n()) %>%
    mutate(n = sum(count),
           proportion = round(count / n, 3)) %>% 
    kable(caption = 'Number of participants with/without missing pain data')
```

## Pain frequency at each week, by data missingness

### Number of participants with pain at each interval

```{r numbers_pain, results = 'asis'}
pain_nested <- pain_nested  %>% 
    mutate(numbers = map2(.x = data,
                          .y = interval_name,
                         ~ .x %>%
                             mutate(pain_status = ifelse(pain_worst > 0,
                                                      yes = 'pain',
                                                      no = 'no pain')) %>% 
                             group_by(any_missing, pain_status) %>% 
                             summarise(count = n()) %>%
                             mutate(pain_status = ifelse(is.na(pain_status),
                                                         yes = 'Missing pain intensity data',
                                                         no = pain_status)) %>% 
                             group_by(any_missing) %>% 
                             mutate(total = sum(count),
                                    proportion = round(count / total, 2)) %>% 
                             kable(caption = str_glue('{str_to_sentence(.y)}: Number of participants with/without missing pain data and who had pain > 0'))))

walk(.x = pain_nested$numbers, ~print(.x))
```

### Plot of pain frequency at each interval

```{r freq_pain_plot}
pain_nested <- pain_nested %>% 
    mutate(xtab = map2(.x = data,
                       .y = interval_name,
                      ~ .x %>% 
                          filter(!is.na(pain_worst)) %>% 
                          mutate(pain_status = ifelse(pain_worst > 0,
                                                      yes = 'pain',
                                                      no = 'no pain')) %>% 
                          xtabs(~ any_missing + pain_status, data = .)))

mosaicplot(pain_nested$xtab[[1]], 
            main = '0 weeks',
            xlab = 'Any missing pain data',
            ylab = 'Pain status')

mosaicplot(pain_nested$xtab[[2]], 
            main = '12 weeks',
            xlab = 'Any missing pain data',
            ylab = 'Pain status')

mosaicplot(pain_nested$xtab[[3]], 
            main = '24 weeks',
            xlab = 'Any missing pain data',
            ylab = 'Pain status')

mosaicplot(pain_nested$xtab[[4]], 
            main = '36 weeks',
            xlab = 'Any missing pain data',
            ylab = 'Pain status')

mosaicplot(pain_nested$xtab[[5]], 
            main = '48 weeks',
            xlab = 'Any missing pain data',
            ylab = 'Pain status')
```

### Chi-squared test of pain frequency at each interval

```{r chi_freq, results = 'asis'}
pain_nested <- pain_nested %>% 
    mutate(chisq = map2(.x = data,
                        .y = interval_name,
                       ~ .x %>% 
                           filter(!is.na(pain_worst)) %>% 
                           mutate(pain_status = ifelse(pain_worst > 0,
                                                       yes = 'pain',
                                                       no = 'no pain')) %>% 
                           xtabs(~ any_missing + pain_status, data = .) %>% 
                           chisq.test(.) %>% 
                           tidy(.) %>% 
                           kable(caption = str_glue('{str_to_sentence(.y)}: missing data by pain frequency'))))

walk(.x = pain_nested$chisq, ~print(.x))
```

## Pain intensity at each week, by data missingness

### Pain intensity at each interval

```{r intensity_pain, results = 'asis'}
pain_nested <- pain_nested %>% 
    mutate(intensity = map2(.x = data,
                            .y = interval_name,
                            ~ .x %>% 
                                filter(pain_worst > 0) %>% 
                                group_by(any_missing) %>% 
                                summarise(median = median(pain_worst),
                                          Q25 = quantile(pain_worst, probs = 0.25),
                                          Q75 = quantile(pain_worst, probs = 0.75)) %>%
                                kable(caption = str_glue('{str_to_sentence(.y)}: Mean IQR pain intensity of participants with/without missing pain data and who had pain > 0'))))

walk(.x = pain_nested$intensity, ~print(.x))
```

### Plot of pain intensity at each interval

```{r plot_pain}
pain_nested <- pain_nested %>% 
    mutate(plot = map2(.x = data,
                       .y = interval_name,
                       ~ .x %>% 
                           filter(pain_worst > 0) %>% 
                           ggplot(data = .) +
                           aes(x = any_missing,
                               y = pain_worst) +
                           geom_boxplot() +
                           geom_point(shape = 21,
                                      size = 3,
                                      fill = '#000000',
                                      alpha = 0.5,
                                      position = position_jitter(height = 0, 
                                                                 width = 0.3)) +
                           labs(title = str_glue('{.y}'),
                                x = 'Any missing data',
                                y = 'Worst pain (11-point NRS)') +
                           scale_y_continuous(limits = c(0, 10))))

print(pain_nested$plot[[1]])
print(pain_nested$plot[[2]])
print(pain_nested$plot[[3]])
print(pain_nested$plot[[4]])
print(pain_nested$plot[[5]])
```

### Wilcoxon sum rank test of pain intensity at each interval

```{r wilcox_pain, results = 'asis'}
pain_nested <- pain_nested %>% 
    mutate(wilcox = map2(.x = data,
                         .y = interval_name,
                         ~ .x %>% 
                             filter(pain_worst > 0) %>% 
                             wilcox.test(data = ., pain_worst ~ any_missing) %>% 
                             tidy(.) %>%
                             kable(caption = str_glue('{str_to_sentence(.y)}: missing pain data by pain > 0'))))

walk(.x = pain_nested$wilcox, ~print(.x))
```

## Pain frequency by treatment group allocation

```{r pain_freq, fig.height = 6, results = 'asis'}
# Process data
freq <- df %>% 
  select(interval_name, group, pain_in_the_last_week) %>% 
  mutate(pain_in_the_last_week = pain_in_the_last_week == 'Yes') %>% 
  group_by(interval_name, group) %>% 
  summarise(count = sum(pain_in_the_last_week == TRUE),
            total = sum(count + sum(pain_in_the_last_week == FALSE)),
            proportion = mean(pain_in_the_last_week)) %>% 
  ungroup()

# Plot data
freq %>% 
  ggplot(data = .) +
  aes(x = group,
      y = proportion) +
  geom_col() +
  labs(subtitle = 'Pain in the last week',
       y = 'Proportion with pain') +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, 
                                   hjust = 0),
        axis.title.x = element_blank()) +
  facet_wrap(~interval_name)

# Analyse data
xfreq <- df %>% 
  group_by(interval_name) %>% 
  nest() %>% 
  mutate(xfreq = map(.x = data,
                     ~ xtabs(~pain_in_the_last_week + group, data = .x))) %>% 
  mutate(chi = map(.x = xfreq,
                   ~ chisq.test(.x) %>% 
                     broom::tidy(.)))

walk2(.x = xfreq$chi,
      .y = xfreq$interval_name,
      ~ print(kable(.x, caption = .y)))
```

No clean pattern in proportion with pain across groups.

## Pain intensity by treatment group allocation

```{r pain_intensity, fig.height = 6, results = 'asis'}
# Process data
intensity <- df %>% 
  select(interval_name, group, pain_worst) %>% 
  filter(pain_worst > 0) 

# Plot data
intensity %>% 
  ggplot(data = .) +
  aes(x = group,
      y = pain_worst) +
  geom_boxplot() +
  labs(subtitle = 'Pain in the last week',
       y = 'Proportion with pain') +
  scale_y_continuous(limits = c(0, 10)) +
  theme(axis.text.x = element_text(angle = 90, 
                                   hjust = 0),
        axis.title.x = element_blank()) +
  facet_wrap(~interval_name)

# Analyse data
test_intensity <- df %>% 
  group_by(interval_name) %>% 
  nest() %>% 
  mutate(kruskal = map(.x = data,
                       ~ kruskal.test(.x$pain_worst ~ .x$group) %>% 
                         broom::tidy(.)))

walk2(.x = test_intensity$kruskal,
      .y = xfreq$interval_name,
      ~ print(kable(.x, caption = .y)))
```

No clean pattern in intensity of worst pain across groups.

## CD4 T-cell count

```{r cd4}
# Tabulate data
df %>% 
  filter(interval_numeric %in% c(0, 24, 48)) %>% 
  select(interval_name, cd4_cells.ul) %>% 
  group_by(interval_name) %>% 
  skim() %>% 
  yank('numeric') %>% 
  select(-skim_variable, -hist, -complete_rate) %>%  
  kable(caption = '7-number summary of CD4 T-cell count (cells/ul)')

# Plot data
df %>% 
  filter(interval_numeric %in% c(0, 24, 48)) %>% 
  ggplot(data = .) +
  aes(x = factor(interval_numeric),
      y = cd4_cells.ul) +
  geom_boxplot() +
  labs(subtitle = 'CD4 T-cell count',
       y = 'CD4 count (cells/ul)',
       x = 'Weeks')
```

## Viral load

```{r vl}
# Tabulate data
df %>% 
  select(interval_name, viral_load_cp.ml) %>% 
  group_by(interval_name) %>% 
  skim() %>% 
  yank('numeric') %>% 
  select(-skim_variable, -hist, -complete_rate) %>% 
  kable(caption = '7-number summary of viral load (copies/ml)')

# Plot data
df %>% 
  ggplot(data = .) +
  aes(x = factor(interval_numeric),
      y = viral_load_cp.ml) +
  geom_boxplot() +
  scale_y_log10() +
  labs(subtitle = 'Viral load',
       y = expression('Viral load [log'[10]*'(copies/ml)]'),
       x = 'Weeks')
```

## General health

Rating of perceived health status on a 5-point Likert scale (1 = poor, 5 = excellent).

```{r gh}
# Tabulate data
df %>% 
  select(interval_name, general_health) %>% 
  group_by(interval_name) %>% 
  skim() %>% 
  yank('numeric') %>% 
  select(-skim_variable, -hist, -complete_rate) %>% 
  kable(caption = '7-number summary of the general health score')

# Plot data
df %>% 
  ggplot(data = .) +
  aes(x = factor(interval_numeric),
      y = general_health) +
  geom_boxplot() +
  labs(subtitle = 'General health perception',
       y = 'GHP score (5-point Likert scale)',
       x = 'Weeks')
```

----

# Session information

```{r session_info}
sessionInfo()
```
